name: Android build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
    secrets:
      KEYSTORE:
        required: true
      SIGNING_KEY_ALIAS:
        required: true
      SIGNING_KEY_PASSWORD:
        required: true
      SIGNING_STORE_PASSWORD:
        required: true

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.KEYSTORE }}
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        mkdir app/keystore
        echo $ENCODED_STRING | base64 -di > app/keystore/keystore.jks

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        log-accepted-android-sdk-licenses: false

    - name: gradlew build
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: chmod u+x ./gradlew && ./gradlew app:assembleRelease

    - name: clean up
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd app
        rm -rf keystore
        rm build/outputs/apk/release/output-metadata.json
        rm -rf build/outputs/apk/release/baselineProfiles

    - name: Push build artifacts
      uses: actions/upload-artifact@v7
      with:
        name: bsquestoneclick-build
        path: |
          app/build/outputs/apk/release