name: Create release

on:
  workflow_dispatch:
    inputs:
      tagName:
        required: true
        type: string
      preRelease:
        required: true
        type: boolean
        default: false

jobs:
  build:
    uses: ./.github/workflows/android-build.yml
    secrets:
      KEYSTORE: ${{ secrets.KEYSTORE }}
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:

    - name: download artifact
      uses: actions/download-artifact@v8
      with:
        name: bsquestoneclick-build
    
    - name: create GitHub release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: ${{ inputs.tagName }}
        release_name: ${{ inputs.tagName }}
        body: |
          Release generated by Actions
        draft: false
        prerelease: ${{ inputs.preRelease }}

    - name: upload android
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app-release.apk
        asset_name: bsdl-${{ inputs.tagName }}.apk
        asset_content_type: application/vnd.android.package-archive